### ISSUE TITLE
Instant crash on Samsung S8+

### ISSUE THREAD

**Issue by namenamenam** [localdesktop/localdesktop#77]
Regardless of if the device is in DeX or not:
-Open app
-"Local Desktop keeps stopping"
No prompt is given to change the WebView implementation either.
Happens on 1.2.6 and 1.2.7

**Comment by mister-teddy** [comment]
Hi @namenamenam, the issue is fixed. Please check the details [here](https://github.com/localdesktop/localdesktop/issues/78#issuecomment-3194494954).

**Comment by namenamenam** [comment]
This still occurs on v1.2.8.
Here's the logcat: https://pastebin.com/7sxutq06

**Comment by mister-teddy** [comment]
```
08-22 13:26:06.644  1774  1774 E AndroidRuntime: java.lang.UnsatisfiedLinkError:
Unable to load native library "/data/app/app.polarbear-k--hOOI1zI0_RQ9KEpS2oQ==/lib/arm64/liblocaldesktop.so":
dlopen failed: cannot locate symbol "AMotionEvent_getActionButton" referenced by "/data/app/app.polarbear-k--hOOI1zI0_RQ9KEpS2oQ==/lib/arm64/liblocaldesktop.so"...
```
The crash issue on your devices was not caused by the webview, but by the usage of `AMotionEvent_getActionButton` on Android < 13, as mentioned in issue #74. Let me explore the options.

**Comment by mister-teddy** [comment]
I fixed the issue with `AMotionEvent_getActionButton`, can you please verify if the crash still happens on your device with [v1.2.9](https://github.com/localdesktop/localdesktop/actions/runs/17188902380)?

I cannot verify with an emulator right now, as it has an issue with EGL.

**Comment by namenamenam** [comment]
The app seems to launch OK now, though it should be noted that the iframe does not show during installation in this build, but the log appears over the whole view (at least in DeX this is the case).

**Comment by namenamenam** [comment]
I guess I celebrated a little too early, since while the installation completes without issue now, the app itself still does not launch. A generic banner for "Local Desktop" shows briefly then the app closes. Here's the logcat:
https://pastebin.com/xdgqfvP5
This could be an issue with a particular component having failed to install, but personally I doubt that's the case.

**Comment by mister-teddy** [comment]
Your logs didn't include any crash or panic. However, I managed to borrow a physical S8 device, and here is the crash log:

```
Failed to create EGL display
```

It is a different variant of EGL error from the one I encountered with the Android 9 emulator, but still an EGL error. Let me see what I can do here.

**Comment by mister-teddy** [comment]
> This still occurs on v1.2.8.

Many things changed since that version. I'm focusinging on v1.5.0 with built-in ptrace now.
